/* Generated by Yosys 0.34+43 (git sha1 d21c464ae, clang 14.0.0-1ubuntu1.1 -fPIC -Os) */

module pes_R2_4BM(clk, load, reset, M, Q, P);
  wire [3:0] _000_;
  wire [7:0] _001_;
  wire [2:0] _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  wire _178_;
  wire _179_;
  wire _180_;
  wire _181_;
  wire _182_;
  wire _183_;
  wire _184_;
  wire _185_;
  wire _186_;
  wire _187_;
  wire _188_;
  wire _189_;
  wire _190_;
  wire _191_;
  wire _192_;
  wire _193_;
  wire _194_;
  wire _195_;
  wire _196_;
  wire _197_;
  wire _198_;
  wire _199_;
  reg [3:0] A = 4'h0;
  reg [2:0] Count = 3'h4;
  input [3:0] M;
  wire [3:0] M;
  reg [3:0] M_temp = 4'h0;
  output [7:0] P;
  reg [7:0] P;
  input [3:0] Q;
  wire [3:0] Q;
  reg Q_minus_one = 1'h0;
  reg [3:0] Q_temp = 4'h0;
  input clk;
  wire clk;
  input load;
  wire load;
  input reset;
  wire reset;
  sky130_fd_sc_hd__clkinv_1 _200_ (
    .A(_109_),
    .Y(_144_)
  );
  sky130_fd_sc_hd__clkinv_1 _201_ (
    .A(_111_),
    .Y(_145_)
  );
  sky130_fd_sc_hd__nor3_1 _202_ (
    .A(_115_),
    .B(_114_),
    .C(_113_),
    .Y(_146_)
  );
  sky130_fd_sc_hd__nor2_1 _203_ (
    .A(_130_),
    .B(_146_),
    .Y(_129_)
  );
  sky130_fd_sc_hd__nor2_1 _204_ (
    .A(_113_),
    .B(_146_),
    .Y(_106_)
  );
  sky130_fd_sc_hd__xor2_1 _205_ (
    .A(_114_),
    .B(_113_),
    .X(_147_)
  );
  sky130_fd_sc_hd__nor2_1 _206_ (
    .A(_146_),
    .B(_147_),
    .Y(_107_)
  );
  sky130_fd_sc_hd__o21a_1 _207_ (
    .A1(_114_),
    .A2(_113_),
    .B1(_115_),
    .X(_108_)
  );
  sky130_fd_sc_hd__nor2b_1 _208_ (
    .A(_146_),
    .B_N(_126_),
    .Y(_148_)
  );
  sky130_fd_sc_hd__a211oi_1 _209_ (
    .A1(_125_),
    .A2(_146_),
    .B1(_148_),
    .C1(_130_),
    .Y(_149_)
  );
  sky130_fd_sc_hd__nor2b_1 _210_ (
    .A(_120_),
    .B_N(_130_),
    .Y(_150_)
  );
  sky130_fd_sc_hd__nor3_1 _211_ (
    .A(_199_),
    .B(_149_),
    .C(_150_),
    .Y(_102_)
  );
  sky130_fd_sc_hd__nor2b_1 _212_ (
    .A(_146_),
    .B_N(_127_),
    .Y(_151_)
  );
  sky130_fd_sc_hd__a211oi_1 _213_ (
    .A1(_126_),
    .A2(_146_),
    .B1(_151_),
    .C1(_130_),
    .Y(_152_)
  );
  sky130_fd_sc_hd__nor2b_1 _214_ (
    .A(_121_),
    .B_N(_130_),
    .Y(_153_)
  );
  sky130_fd_sc_hd__nor3_1 _215_ (
    .A(_199_),
    .B(_152_),
    .C(_153_),
    .Y(_103_)
  );
  sky130_fd_sc_hd__nor2b_1 _216_ (
    .A(_146_),
    .B_N(_128_),
    .Y(_154_)
  );
  sky130_fd_sc_hd__a211oi_1 _217_ (
    .A1(_127_),
    .A2(_146_),
    .B1(_154_),
    .C1(_130_),
    .Y(_155_)
  );
  sky130_fd_sc_hd__nor2b_1 _218_ (
    .A(_122_),
    .B_N(_130_),
    .Y(_156_)
  );
  sky130_fd_sc_hd__nor3_1 _219_ (
    .A(_199_),
    .B(_155_),
    .C(_156_),
    .Y(_104_)
  );
  sky130_fd_sc_hd__nand2b_1 _220_ (
    .A_N(_124_),
    .B(_125_),
    .Y(_157_)
  );
  sky130_fd_sc_hd__nor2b_1 _221_ (
    .A(_125_),
    .B_N(_124_),
    .Y(_158_)
  );
  sky130_fd_sc_hd__nor2_1 _222_ (
    .A(_146_),
    .B(_158_),
    .Y(_159_)
  );
  sky130_fd_sc_hd__and2_0 _223_ (
    .A(_157_),
    .B(_159_),
    .X(_160_)
  );
  sky130_fd_sc_hd__a21oi_1 _224_ (
    .A1(_109_),
    .A2(_116_),
    .B1(_146_),
    .Y(_161_)
  );
  sky130_fd_sc_hd__nor2b_1 _225_ (
    .A(_109_),
    .B_N(_116_),
    .Y(_162_)
  );
  sky130_fd_sc_hd__o21ai_0 _226_ (
    .A1(_109_),
    .A2(_116_),
    .B1(_161_),
    .Y(_163_)
  );
  sky130_fd_sc_hd__nand2_1 _227_ (
    .A(_128_),
    .B(_146_),
    .Y(_164_)
  );
  sky130_fd_sc_hd__a21oi_1 _228_ (
    .A1(_163_),
    .A2(_164_),
    .B1(_160_),
    .Y(_165_)
  );
  sky130_fd_sc_hd__a211oi_1 _229_ (
    .A1(_109_),
    .A2(_160_),
    .B1(_165_),
    .C1(_130_),
    .Y(_166_)
  );
  sky130_fd_sc_hd__nor2b_1 _230_ (
    .A(_123_),
    .B_N(_130_),
    .Y(_167_)
  );
  sky130_fd_sc_hd__nor3_1 _231_ (
    .A(_199_),
    .B(_166_),
    .C(_167_),
    .Y(_105_)
  );
  sky130_fd_sc_hd__nand2_1 _232_ (
    .A(_110_),
    .B(_117_),
    .Y(_168_)
  );
  sky130_fd_sc_hd__xor2_1 _233_ (
    .A(_110_),
    .B(_117_),
    .X(_169_)
  );
  sky130_fd_sc_hd__a21oi_1 _234_ (
    .A1(_109_),
    .A2(_116_),
    .B1(_169_),
    .Y(_170_)
  );
  sky130_fd_sc_hd__nand2_1 _235_ (
    .A(_116_),
    .B(_169_),
    .Y(_171_)
  );
  sky130_fd_sc_hd__nand3_1 _236_ (
    .A(_109_),
    .B(_116_),
    .C(_169_),
    .Y(_172_)
  );
  sky130_fd_sc_hd__nor2b_1 _237_ (
    .A(_146_),
    .B_N(_158_),
    .Y(_173_)
  );
  sky130_fd_sc_hd__nand2b_1 _238_ (
    .A_N(_146_),
    .B(_158_),
    .Y(_174_)
  );
  sky130_fd_sc_hd__nand2_1 _239_ (
    .A(_172_),
    .B(_173_),
    .Y(_175_)
  );
  sky130_fd_sc_hd__nor2_1 _240_ (
    .A(_170_),
    .B(_175_),
    .Y(_176_)
  );
  sky130_fd_sc_hd__nor2_1 _241_ (
    .A(_146_),
    .B(_157_),
    .Y(_177_)
  );
  sky130_fd_sc_hd__nor4_1 _242_ (
    .A(_146_),
    .B(_157_),
    .C(_162_),
    .D(_169_),
    .Y(_178_)
  );
  sky130_fd_sc_hd__a21oi_1 _243_ (
    .A1(_171_),
    .A2(_177_),
    .B1(_109_),
    .Y(_179_)
  );
  sky130_fd_sc_hd__nor3_1 _244_ (
    .A(_173_),
    .B(_178_),
    .C(_179_),
    .Y(_180_)
  );
  sky130_fd_sc_hd__o21bai_1 _245_ (
    .A1(_176_),
    .A2(_180_),
    .B1_N(_160_),
    .Y(_181_)
  );
  sky130_fd_sc_hd__a21oi_1 _246_ (
    .A1(_110_),
    .A2(_160_),
    .B1(_130_),
    .Y(_182_)
  );
  sky130_fd_sc_hd__a221oi_1 _247_ (
    .A1(_130_),
    .A2(_144_),
    .B1(_181_),
    .B2(_182_),
    .C1(_199_),
    .Y(_098_)
  );
  sky130_fd_sc_hd__nand2_1 _248_ (
    .A(_111_),
    .B(_118_),
    .Y(_183_)
  );
  sky130_fd_sc_hd__xnor2_1 _249_ (
    .A(_111_),
    .B(_118_),
    .Y(_184_)
  );
  sky130_fd_sc_hd__nand2b_1 _250_ (
    .A_N(_117_),
    .B(_110_),
    .Y(_185_)
  );
  sky130_fd_sc_hd__o21ai_0 _251_ (
    .A1(_162_),
    .A2(_169_),
    .B1(_185_),
    .Y(_186_)
  );
  sky130_fd_sc_hd__xnor2_1 _252_ (
    .A(_184_),
    .B(_186_),
    .Y(_187_)
  );
  sky130_fd_sc_hd__o21ai_0 _253_ (
    .A1(_110_),
    .A2(_177_),
    .B1(_174_),
    .Y(_188_)
  );
  sky130_fd_sc_hd__a21o_1 _254_ (
    .A1(_177_),
    .A2(_187_),
    .B1(_188_),
    .X(_189_)
  );
  sky130_fd_sc_hd__nand3_1 _255_ (
    .A(_168_),
    .B(_172_),
    .C(_184_),
    .Y(_190_)
  );
  sky130_fd_sc_hd__a21o_1 _256_ (
    .A1(_168_),
    .A2(_172_),
    .B1(_184_),
    .X(_191_)
  );
  sky130_fd_sc_hd__nand3_1 _257_ (
    .A(_173_),
    .B(_190_),
    .C(_191_),
    .Y(_192_)
  );
  sky130_fd_sc_hd__a21oi_1 _258_ (
    .A1(_189_),
    .A2(_192_),
    .B1(_160_),
    .Y(_193_)
  );
  sky130_fd_sc_hd__a211oi_1 _259_ (
    .A1(_111_),
    .A2(_160_),
    .B1(_193_),
    .C1(_130_),
    .Y(_194_)
  );
  sky130_fd_sc_hd__nor2b_1 _260_ (
    .A(_110_),
    .B_N(_130_),
    .Y(_195_)
  );
  sky130_fd_sc_hd__nor3_1 _261_ (
    .A(_199_),
    .B(_194_),
    .C(_195_),
    .Y(_099_)
  );
  sky130_fd_sc_hd__nor2_1 _262_ (
    .A(_145_),
    .B(_118_),
    .Y(_196_)
  );
  sky130_fd_sc_hd__a21o_1 _263_ (
    .A1(_184_),
    .A2(_186_),
    .B1(_196_),
    .X(_197_)
  );
  sky130_fd_sc_hd__xor2_1 _264_ (
    .A(_112_),
    .B(_119_),
    .X(_198_)
  );
  sky130_fd_sc_hd__a211oi_1 _265_ (
    .A1(_184_),
    .A2(_186_),
    .B1(_196_),
    .C1(_198_),
    .Y(_131_)
  );
  sky130_fd_sc_hd__a2111oi_0 _266_ (
    .A1(_197_),
    .A2(_198_),
    .B1(_131_),
    .C1(_157_),
    .D1(_146_),
    .Y(_132_)
  );
  sky130_fd_sc_hd__nor2_1 _267_ (
    .A(_111_),
    .B(_177_),
    .Y(_133_)
  );
  sky130_fd_sc_hd__o21ai_0 _268_ (
    .A1(_132_),
    .A2(_133_),
    .B1(_174_),
    .Y(_134_)
  );
  sky130_fd_sc_hd__nand3_1 _269_ (
    .A(_183_),
    .B(_191_),
    .C(_198_),
    .Y(_135_)
  );
  sky130_fd_sc_hd__a21o_1 _270_ (
    .A1(_183_),
    .A2(_191_),
    .B1(_198_),
    .X(_136_)
  );
  sky130_fd_sc_hd__nand3_1 _271_ (
    .A(_173_),
    .B(_135_),
    .C(_136_),
    .Y(_137_)
  );
  sky130_fd_sc_hd__nand3b_1 _272_ (
    .A_N(_160_),
    .B(_134_),
    .C(_137_),
    .Y(_138_)
  );
  sky130_fd_sc_hd__a21oi_1 _273_ (
    .A1(_112_),
    .A2(_160_),
    .B1(_130_),
    .Y(_139_)
  );
  sky130_fd_sc_hd__a221oi_1 _274_ (
    .A1(_130_),
    .A2(_145_),
    .B1(_138_),
    .B2(_139_),
    .C1(_199_),
    .Y(_100_)
  );
  sky130_fd_sc_hd__nor2_1 _275_ (
    .A(_112_),
    .B(_177_),
    .Y(_140_)
  );
  sky130_fd_sc_hd__o21ai_0 _276_ (
    .A1(_132_),
    .A2(_140_),
    .B1(_174_),
    .Y(_141_)
  );
  sky130_fd_sc_hd__a21oi_1 _277_ (
    .A1(_137_),
    .A2(_141_),
    .B1(_130_),
    .Y(_142_)
  );
  sky130_fd_sc_hd__nor2b_1 _278_ (
    .A(_112_),
    .B_N(_130_),
    .Y(_143_)
  );
  sky130_fd_sc_hd__nor3_1 _279_ (
    .A(_199_),
    .B(_142_),
    .C(_143_),
    .Y(_101_)
  );
  always @(posedge clk)
    A[0] <= _000_[0];
  always @(posedge clk)
    A[1] <= _000_[1];
  always @(posedge clk)
    A[2] <= _000_[2];
  always @(posedge clk)
    A[3] <= _000_[3];
  always @(posedge clk)
    P[0] <= _001_[0];
  always @(posedge clk)
    P[1] <= _001_[1];
  always @(posedge clk)
    P[2] <= _001_[2];
  always @(posedge clk)
    P[3] <= _001_[3];
  always @(posedge clk)
    P[4] <= _000_[0];
  always @(posedge clk)
    P[5] <= _000_[1];
  always @(posedge clk)
    P[6] <= _000_[2];
  always @(posedge clk)
    P[7] <= _000_[3];
  always @(posedge clk)
    if (reset) Q_minus_one <= 1'h0;
    else if (_003_) Q_minus_one <= Q_temp[0];
  always @(posedge clk)
    Q_temp[0] <= _001_[0];
  always @(posedge clk)
    Q_temp[1] <= _001_[1];
  always @(posedge clk)
    Q_temp[2] <= _001_[2];
  always @(posedge clk)
    Q_temp[3] <= _001_[3];
  always @(posedge clk)
    if (reset) M_temp[0] <= 1'h0;
    else if (load) M_temp[0] <= M[0];
  always @(posedge clk)
    if (reset) M_temp[1] <= 1'h0;
    else if (load) M_temp[1] <= M[1];
  always @(posedge clk)
    if (reset) M_temp[2] <= 1'h0;
    else if (load) M_temp[2] <= M[2];
  always @(posedge clk)
    if (reset) M_temp[3] <= 1'h0;
    else if (load) M_temp[3] <= M[3];
  always @(posedge clk)
    if (reset) Count[0] <= 1'h0;
    else if (!load) Count[0] <= _002_[0];
  always @(posedge clk)
    if (reset) Count[1] <= 1'h0;
    else if (!load) Count[1] <= _002_[1];
  always @(posedge clk)
    if (reset) Count[2] <= 1'h1;
    else if (!load) Count[2] <= _002_[2];
  assign _001_[7:4] = _000_;
  assign _124_ = Q_minus_one;
  assign _125_ = Q_temp[0];
  assign _115_ = Count[2];
  assign _114_ = Count[1];
  assign _113_ = Count[0];
  assign _130_ = load;
  assign _003_ = _129_;
  assign _002_[0] = _106_;
  assign _002_[1] = _107_;
  assign _002_[2] = _108_;
  assign _199_ = reset;
  assign _120_ = Q[0];
  assign _126_ = Q_temp[1];
  assign _001_[0] = _102_;
  assign _121_ = Q[1];
  assign _127_ = Q_temp[2];
  assign _001_[1] = _103_;
  assign _122_ = Q[2];
  assign _128_ = Q_temp[3];
  assign _001_[2] = _104_;
  assign _123_ = Q[3];
  assign _109_ = A[0];
  assign _116_ = M_temp[0];
  assign _001_[3] = _105_;
  assign _110_ = A[1];
  assign _117_ = M_temp[1];
  assign _000_[0] = _098_;
  assign _111_ = A[2];
  assign _118_ = M_temp[2];
  assign _000_[1] = _099_;
  assign _112_ = A[3];
  assign _119_ = M_temp[3];
  assign _000_[2] = _100_;
  assign _000_[3] = _101_;
endmodule
